dist: trusty
language: c

before_install:
    - sudo apt-get install -y build-essential git 
    - git clone -b OpenSSL_1_1_1k --depth 1 https://github.com/openssl/openssl.git && cd openssl && ./config && make -j2 && sudo make install >/dev/null 2>&1 && cd ..
    - sudo ldconfig

script:
    - make all
    - make tests
